@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
/' 13장 : 더하기 기능 (추가매개변수)
'/
class Money
interface Expression
class Bank
class Sum

Expression <|.. Money
Money <.. Bank
Expression <|.. Sum

class Money{
 #currency : String
 #multiplication : int
 +Money(amount : int, currency : String)
 +dollar(amount : int) : {static} Money
 +franc(amount : int) : {static} Money
 +eqals(objects : Object) : boolean
 +currency() : String
 +toString() : String
 +times(multiplication : int) : Money
 +plus(addend : Money) : Expression
 +reduce(to : String) : Money
}
interface Expression{
 +plus(added : Money) Expression
 +reduce(to : String) : Money
}
class Bank{
 +reduce(source : Expression, to : String) : Money
}
class Sum{
 +augend : Money
 +addend : Money
 +Sum(augend : Money, addend : Money)
 +reduce(to : String) : Money
}
@enduml